/* IAP – Integrált Automatika Program
   Központi tanév-naptár, 2026/2027.
*/
(function () {
  'use strict';
  const IAP_NAPTAR={tanev:'2026/2027',elsoTanitasNap:'2026-09-01',utolsoTanitasNap:'2027-06-15',szunetek:[{nev:'Őszi szünet',tol:'2026-10-23',ig:'2026-11-01'},{nev:'Téli szünet',tol:'2026-12-19',ig:'2027-01-03'},{nev:'Tavaszi szünet',tol:'2027-03-25',ig:'2027-04-04'}],maxHet:36};
  const TANTARGY_OLDALAK=['villamos9.html','villamos10.html','gepeszet10.html','analog11.html','elektrotechnika11.html','villamosszereles11.html','plc.html','folyamatiranyitas12.html','epuletvillamossag13.html','villamosmuvek13.html'];
  function datum(s){const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12,0,0)}
  function napKezdete(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate(),12,0,0)}
  function hetfo(d){const x=napKezdete(d),nap=x.getDay();x.setDate(x.getDate()-(nap===0?6:nap-1));return x}
  function szunetben(d){return IAP_NAPTAR.szunetek.some(s=>d>=datum(s.tol)&&d<=datum(s.ig))}
  function tanitasiHetVan(h){const e=datum(IAP_NAPTAR.elsoTanitasNap),u=datum(IAP_NAPTAR.utolsoTanitasNap);for(let i=0;i<5;i++){const d=new Date(h);d.setDate(d.getDate()+i);if(d>=e&&d<=u&&!szunetben(d))return true}return false}
  function aktualisIAPHet(ma=new Date()){const e=datum(IAP_NAPTAR.elsoTanitasNap),u=datum(IAP_NAPTAR.utolsoTanitasNap),m=napKezdete(ma);if(m<e||m>u)return null;const cel=hetfo(m);let h=hetfo(e),n=0;while(h<=cel){if(tanitasiHetVan(h))n++;if(h.getTime()===cel.getTime()){if(!tanitasiHetVan(h))return null;return Math.min(n,IAP_NAPTAR.maxHet)}h.setDate(h.getDate()+7)}return null}
  function stilusBetoltese(){if(document.getElementById('iap-aktualis-het-stilus'))return;const s=document.createElement('style');s.id='iap-aktualis-het-stilus';s.textContent=`.het{position:relative}.het.aktualis-het,.het.aktualis{margin:12px 0;padding:42px 18px 18px;background:linear-gradient(135deg,#e8f3ff,#f8fbff);border:2px solid #1976d2;border-radius:14px;box-shadow:0 10px 28px #1976d22b}.het.aktualis-het::before,.het.aktualis::before{content:'●  AKTUÁLIS HÉT';position:absolute;top:10px;left:88px;padding:5px 12px;border-radius:999px;background:#1976d2;color:#fff;font-size:.78rem;font-weight:800;letter-spacing:.04em;z-index:1}.het.aktualis-het .het-szam,.het.aktualis .het-szam{background:linear-gradient(135deg,#0d47a1,#2196f3)!important;box-shadow:0 5px 14px #1976d244}@media(max-width:650px){.het.aktualis-het,.het.aktualis{padding-top:48px}.het.aktualis-het::before,.het.aktualis::before{left:14px}}`;document.head.appendChild(s)}
  function kiemelAktualisHet(){stilusBetoltese();const a=aktualisIAPHet();document.querySelectorAll('.het').forEach(h=>h.classList.remove('aktualis-het','aktualis'));if(!a)return;document.querySelectorAll('.het').forEach(h=>{const e=h.querySelector('.het-szam');if(e&&parseInt(e.textContent.trim(),10)===a)h.classList.add('aktualis-het')})}
  function subjectDesignBetoltese(){const oldal=location.pathname.split('/').pop().toLowerCase();if(!TANTARGY_OLDALAK.includes(oldal)||document.getElementById('iap-subject-design'))return;const l=document.createElement('link');l.id='iap-subject-design';l.rel='stylesheet';l.href='./iap-subject-design.css?v=4';document.head.appendChild(l)}
  function kihivasMotorBetoltese(){const oldal=location.pathname.split('/').pop().toLowerCase();if(!TANTARGY_OLDALAK.includes(oldal)||oldal==='villamos9.html')return;if(window.IAPKihivas){window.IAPKihivas.autoInit?.();return}if(document.getElementById('iap-kihivas-motor-loader')||document.querySelector('script[src*="iap-kihivas-motor.js"]'))return;const s=document.createElement('script');s.id='iap-kihivas-motor-loader';s.src='./iap-kihivas-motor.js?v=4';s.async=false;s.onload=()=>window.IAPKihivas?.autoInit?.();s.onerror=()=>console.error('IAP: a központi kihívásmotor nem tölthető be.');document.body.appendChild(s)}
  function haladasKovetese(){const oldal=location.pathname.split('/').pop().toLowerCase();if(!TANTARGY_OLDALAK.includes(oldal))return;const hetek=[...document.querySelectorAll('.het')];if(!hetek.length)return;const tantargy=(document.querySelector('.tantargy-fejlec h2')?.textContent||document.querySelector('header h1')?.textContent||document.title||'IAP tantárgy').trim();
    function adat(h){const m=(h.querySelector('.het-szam')?.textContent||'').match(/\d+/);if(!m)return null;const het=+m[0];h.id=`het-${het}`;const tema=(h.querySelector('.het-tartalom h3')?.textContent||h.querySelector('h3')?.textContent||`${het}. hét`).trim();return{oldal,tantargy,het,tema,hash:`#het-${het}`,ido:Date.now()}}
    function ment(h){const a=adat(h);if(!a)return;try{localStorage.setItem('iap_folytatom',JSON.stringify(a))}catch(e){}}
    hetek.forEach(h=>{adat(h);h.addEventListener('pointerdown',()=>ment(h));h.querySelectorAll('a,button').forEach(x=>x.addEventListener('click',()=>ment(h),true))});
    const hash=location.hash.match(/het-(\d+)/);if(hash){const h=document.getElementById(`het-${+hash[1]}`);if(h){ment(h);setTimeout(()=>h.scrollIntoView({behavior:'smooth',block:'center'}),120)}}
    else {const a=aktualisIAPHet();const h=a&&document.getElementById(`het-${a}`);if(h)ment(h)}
  }
  window.IAP_NAPTAR=IAP_NAPTAR;window.aktualisIAPHet=aktualisIAPHet;window.kiemelAktualisIAPHet=kiemelAktualisHet;window.kiemelAktualisHet=kiemelAktualisHet;
  function indul(){subjectDesignBetoltese();kiemelAktualisHet();kihivasMotorBetoltese();haladasKovetese()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',indul);else indul();
})();